llmdataset/urls.py
from django.contrib import admin
from django.urls import path

import sys

sys.path.append("setcollect//function")
from setcollect import views
from setcollect.function import (
    user_manage,
    question_manage,
    title_manage,
    label_collection,
    word_manage,
    chat_robot,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    # main views
    path("info/main/", views.info_main),
    path("test/", views.test),
    # user manage
    path("login/", user_manage.login),
    path("info/list/", user_manage.info_list),
    path("info/add/", user_manage.info_add),
    path("info/delete/", user_manage.info_delete),
    path("info/<int:nid>/edit/", user_manage.info_edit),
    path("user/list/", user_manage.user_list),
    # question manage
    path("question/list/", question_manage.question_list),
    path("question/add/", question_manage.question_add),
    path("question/delete/", question_manage.question_delete),
    path("question/<int:nid>/edit/", question_manage.question_edit),
    # label manage
    path("label/list/", label_collection.label_list),
    path("label/add/", label_collection.label_add),
    path("label/delete/", label_collection.label_delete),
    path("label/search/", label_collection.search_by_label),
    path("label/search/search/", label_collection.search_search, name="search_search"),
    # title manage
    path("title/list/", title_manage.title_list),
    path("title/add/", title_manage.title_add),
    path("title/delete/", title_manage.title_delete),
    path("title/<int:nid>/edit/", title_manage.title_edit),
    
    #word manage
    path('word/list/', word_manage.word_list),
    path('word/add/', word_manage.word_add),
    path("word/delete/", word_manage.word_delete),
    path('word/<int:nid>/edit/', word_manage.word_edit),
    
    
    #chat robot
    path('chatbot/', chat_robot.chatbot_view, name='chatbot'),
    path('chatbot/chat/', chat_robot.chat_bot_response, name='chat_bot'),
    path('chatbot/eval/', chat_robot.chat_eval),
    
    #conversation manage
    path("conversation/list/", views.conversation_list),

    #evaluation page
    path('evaluation/', views.evaluation, name='evaluation'),
    path('rate/', views.rate, name='rate')
    
    #chatbot manage
    #path('chatbot/', views.chatbot_view, name='chatbot'),

    # path('chatbot/response/', views.handle_input, name='handle_input')
       
]

setcollect/models.py
from django.db import models


class UserInfo(models.Model):
    role_choice = (
        (1, "admin"),
        (2, "user"),
    )

    name = models.CharField(max_length=32)
    password = models.CharField(max_length=64)
    role = models.SmallIntegerField(verbose_name="choice of role", choices=role_choice)


class Conversation(models.Model):
    name = models.TextField()


class Question(models.Model):
    question = models.TextField()
    conversation = models.ForeignKey("Conversation", on_delete=models.CASCADE)
    question_tag = models.ManyToManyField("Tag")


class LModel(models.Model):
    model_choice = (
        (1, "ChatGPT"),
        (2, "iflytek spark"),
        (3, "Human"),
        (4, "Mudu V1.0"),
        (5, "Mudu V2.0"),
        (6, "Mudu V3.0"),
        (7, "Mudu V4.0"),
        (8, "Mudu V5.0"),
        (9, "Mudu V6.0"),
    )

    lmodel = models.SmallIntegerField(
        verbose_name="choice of model", choices=model_choice
    )
    answer = models.TextField()
    question = models.ForeignKey("Question", on_delete=models.CASCADE)
    evaluation = models.IntegerField()


class Tag(models.Model):
    tag_degree = models.CharField(max_length=16 , null=True) 
    tag_classification = models.CharField(max_length=16)
    tag_name = models.CharField(max_length=32)


class Word(models.Model):
    word = models.CharField(max_length=128)
    word_tag = models.ManyToManyField("Tag")


class Sentences(models.Model):
    sentences = models.TextField()
    words = models.ManyToManyField("Word")
    sentences_tag = models.ManyToManyField("Tag")


class Title(models.Model):
    title = models.TextField()
    words = models.ManyToManyField("Word")
    sentences = models.ManyToManyField("Sentences")
    title_tag = models.ManyToManyField("Tag")
    mapping = models.BooleanField(default=False)

setcollect/views.py
from django.shortcuts import render, HttpResponse
from .models import Question, LModel
from django.shortcuts import redirect
from django.contrib import messages

http_address = 'http://127.0.0.1:8000/'

def info_main(request):
    return render(request, "info_main.html")

def test(request):
    return render(request, "test.html")
    
def conversation_list(request):
    return render(request, "conversation_list.html")


def chatbot_view(request):
    return render(request, 'chat_bot.html')

def handle_input(request):
    ai_response = "你好，我是Mudu作文助手。"
    if request.method == 'POST':
        user_input = request.body.decode('utf-8')

        # Process the user input and generate a response
        #在这里连接模型，把模型生成的产出string赋值给ai_response
        ai_response = "你好，我是Mudu作文助手。"

    return HttpResponse(ai_response)



def evaluation(request):
    # 获取所有唯一的问题文本
    unique_questions = Question.objects.values_list('question', flat=True).distinct()

    selected_question_text = request.GET.get('question_text')
    answers_by_model = {}
    current_ratings = {}
    if selected_question_text:
        # 获取每个模型的答案和当前评估值
        for model_choice in LModel.model_choice:
            model_id = model_choice[0]
            answers = LModel.objects.filter(question__question=selected_question_text, lmodel=model_id)
            answers_by_model[model_id] = answers[0].answer if answers else "This question does not have answer from this model."  # 如果没有答案，就使用默认文本
            current_ratings[model_id] = answers[0].evaluation if answers else None

    context = {
        'all_questions': unique_questions,
        'answers_by_model': answers_by_model,
        'selected_question_text': selected_question_text,
        'current_ratings': current_ratings  # 添加当前评估值到上下文
    }

    return render(request, 'evaluation.html', context)

def rate(request):
    if request.method == "POST":
        # 获取问题的文本
        question_text = request.POST.get('question_text')

        # 获取所有的评分值
        rating_1 = request.POST.get('rating_1')
        rating_2 = request.POST.get('rating_2')
        rating_4 = request.POST.get('rating_4')
        rating_9 = request.POST.get('rating_9')

        # 根据问题文本获取相关的问题ID
        related_questions = Question.objects.filter(question=question_text)

        # 更新数据库记录
        for question in related_questions:
            if rating_1:
                LModel.objects.filter(lmodel=1, question=question).update(evaluation=rating_1)
            if rating_2:
                LModel.objects.filter(lmodel=2, question=question).update(evaluation=rating_2)
            if rating_4:
                LModel.objects.filter(lmodel=4, question=question).update(evaluation=rating_4)
            if rating_9:
                LModel.objects.filter(lmodel=9, question=question).update(evaluation=rating_9)

    # 重定向回evaluation页面，以便用户可以继续选择和评价问题
    return redirect(f"/evaluation/?question_text={question_text}")

setcollect/templates/info_add.html
{% extends 'layout.html' %}

{% block content %}


<div>
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create new user</h3>
            </div>

            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">User name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="user" placeholder="User name"
                            value="{{ request.GET.user }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="pwd" placeholder="Password"
                            value="{{ request.GET.pwd }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Role</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="role" value="{{ request.GET.role }}">
                            <option value="2">User</option>
                            <option value="1">administer</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Sign in</button>
                    </div>
                </div>
                {% if messages %}
                <div class="alert alert-danger" role="alert">
                    {% for message in messages %}
                    {{ message }}
                    {% endfor %}
                </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>


{% endblock %}

setcollect/templates/info_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
</body>
</html>

setcollect/templates/info_list.html
{% extends 'layout.html' %}

{% block content %}


<div>
    <div class="container">
        <div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/info/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Create new Account
            </a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                User list
            </div>


            <!-- Table -->
            <div style="overflow: auto; max-height: 400px;">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>User name</th>
                            <th>Password</th>
                            <th>Role</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in data_list %}
                        <tr>
                            <td>{{ obj.id }}</td>
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.password }}</td>
                            <td>{{ obj.get_role_display }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs"
                                    href="/info/{{ obj.id }}/edit/">Edit</a>
                                <a class="btn btn-danger btn-xs"
                                    href="/info/delete/?nid={{obj.id}}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>

{% endblock %}

setcollect/templates/info_main.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>Welcome to LLM Dataset system!</h1>
        <p>You can enter questions and get answers from three conversational language AI's 
            and give each question a separate tag to improve the accuracy of the results. 
            The program is primarily used to tutor pre-18 students in composition studies and to reinforce the ability to write essays.</p>
        <p><a class="btn btn-primary btn-lg" href="/chatbot/" role="button">Start Now!</a></p>
    </div>
</div>

{% endblock %}

setcollect/templates/label_list.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <div class="container">
        <div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/label/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Create new Label
            </a>
        </div>

        <div style="margin-bottom: 30px;">
            <a class="btn btn-success" href="/label/search/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Search by label
            </a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Question list
            </div>


            <!-- Table -->
            <div style="overflow: auto; max-height: 400px;">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Classification</th>
                            <th>Tags</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tag in data_list %}
                        <tr>
                            <td>{{ tag.id }}</td>
                            <td>{{ tag.tag_classification }}</td>
                            <td>{{ tag.tag_name }}</td>
                            <td>
                                <a class="btn btn-danger btn-xs"
                                    href="/label/delete/?nid={{tag.id}}">Delete</a>
                            </td>
                            {% endfor %}
                    </tbody>
                </table>
             </div>


        </div>

    </div>
</div>

{% endblock %}

setcollect/templates/label_search.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Label Search</h3>
            </div>

            <form action="search/" method="get" class="form-horizontal">
                <div class="form-group">
                    <label for="tag_search" class="col-sm-2 control-label">Search by Tag:</label>
                    <div class="col-sm-10">
                        <input id="tag_search" type="text" class="form-control" name="tag_name" placeholder="Enter a tag">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" class="btn btn-primary" value="Search">
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script>
        // Autocomplete function
        function autocomplete(inp, arr) {
            inp.addEventListener("input", function (e) {
                var a, b, i, val = this.value;

                closeAllLists();
                if (!val) { return false; }
                a = document.createElement("DIV");
                a.setAttribute("id", this.id + "autocomplete-list");
                a.setAttribute("class", "autocomplete-items");

                this.parentNode.appendChild(a);
                for (i = 0; i < arr.length; i++) {
                    if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                        b = document.createElement("DIV");
                        b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
                        b.innerHTML += arr[i].substr(val.length);
                        b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";

                        b.addEventListener("click", function (e) {
                            inp.value = this.getElementsByTagName("input")[0].value;
                            closeAllLists();
                        });

                        a.appendChild(b);
                    }
                }
            });

            function closeAllLists(elmnt) {
                var x = document.getElementsByClassName("autocomplete-items");
                for (var i = 0; i < x.length; i++) {
                    if (elmnt != x[i] && elmnt != inp) {
                        x[i].parentNode.removeChild(x[i]);
                    }
                }
            }

            document.addEventListener("click", function (e) {
                closeAllLists(e.target);
            });
        }

        window.onload = function () {
            var tags = { all_tags };
            autocomplete(document.getElementById("tag_search"), tags);
        }
    </script>
{% endblock %}

setcollect/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User log in</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="account">
        <h2>User log in</h2>
        <form method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label>User name</label>
                {{ form.username }}
                <span style="color: red;">{{ form.username.errors.0 }}</span>
            </div>

            <div class="form-group">
                <label>Password</label>
                {{ form.password }}
                <span style="color: red;">{{ form.password.errors.0 }}</span>
            </div>

            <input type="submit" value="log in" class="btn btn-primary">
        </form>
    </div>

</body>

</html>

setcollect/templates/title_add.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <div class="container">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Add Title
            </div>

            <!-- Form -->
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title:</label>
                    <input id="title" type="text" class="form-control" name="title">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>

    </div>
</div>

{% endblock %}

setcollect/templates/title_edit.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Edit Title</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" placeholder="Title"
                            value="{{ row_object.title }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Sentences</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="sentences" placeholder="Sentences"
                            value="{{ sentence_pool.sentence }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Words</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="words" placeholder="Words"
                            value="{{ word_pool.sentence }}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

setcollect/templates/title_list.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <div class="container">
        <div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/title/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Create new title
            </a>
        </div>
        <div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/title/list/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Mapping
            </a>
        </div>
        <div style="overflow: auto; max-height: 400px;">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Title ID</th>
                        <th>Title</th>
                        <th>Sentences</th>
                        <th>Words</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    {% for title in titles %}
                    <tr>
                        <td> {{ title.title.id }}</td>
                        <td>{{ title.title.title }}</td>
                        <td>
                            {% for sentence in title.sentences %}
                            {{ sentence.sentences }}<br>
                            {% empty %}
                            No sentences for this title.
                            {% endfor %}
                        </td>
                        <td>
                            {% for word in title.word %}
                            {{ word.word }}<br>
                            {% empty %}
                            No words for this title.
                            {% endfor %}
                        <td>
                            <a class="btn btn-primary btn-xs"
                                href="/title/{{ title.title.id }}/edit/">Edit</a>
                            <a class="btn btn-danger btn-xs"
                                href="/title/delete/?nid={{title.title.id}}">Delete</a>
                        </td>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

setcollect/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <div class="container">
        <div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/question/user/tag/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Add lables
            </a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Question list
            </div>


            <!-- Table -->
            <div style="overflow: auto; max-height: 400px;">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Question</th>
                            <th>Labels</th>
                            <th>Model</th>
                            <th>Answer</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in data_list %}
                        {% for lmodel in obj.lmodel_set.all %}
                        <tr>
                            <td>{{ obj.id }}</td>
                            <td>{{ obj.question }}</td>
                            <td>{{ obj.tag_name }}</td>
                            <td>{{ lmodel.get_lmodel_display }}</td>
                            <td>{{ lmodel.answer }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td>{{ obj.id }}</td>
                            <td>{{ obj.question }}</td>
                            <td>{{ obj.tag_name }}</td>
                            <td colspan="2">No answers for this question.</td>
                        </tr>
                        {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>

    </div>
</div>

{% endblock %}

setcollect/templates/word_add.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create new Word</h3>
            </div>

            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Word</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="word" placeholder="Add Word">
                    </div>
                </div>
                <!-- <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Classification</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="tag_classification" placeholder="Add Classification">
                    </div>
                </div> -->
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Label</label>
                    <div class="col-sm-10">
                        <input type="text" id="tagInput" class="form-control" placeholder="Add label"
                            value="{{ request.GET.tag_name }}" onkeydown="addTagFromInput(event)">
                        <input type="hidden" id="tagsField" name="tag_name" value="{{ request.GET.tag_name }}">

                        <div id="tagsDisplay" style="margin-top: 10px;"></div>

                        <div id="tagButtons" style="margin-top: 10px; overflow: auto; max-height: 300px;">
                            {% for tag in label_pool %}
                            <button type="button" onclick="addTagFromInput(event)" class="btn btn-secondary btn-sm"
                                style="background-color: #99ff33; margin-bottom: 5px">{{ tag.tag_name }}</button>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Create new Word</button>
                    </div>
                </div>

                {% if messages %}
                <div class="alert alert-danger" role="alert">
                    {{ messages }}
                </div>
                {% endif %}

            </form>


        </div>
    </div>
</div>

<script>
    var tagButtons = Array.from(document.getElementById('tagButtons').children);
    var selectedTags = [];

    function addTagFromInput(event) {
        if (event.key === 'Enter') {
            event.preventDefault();
            var tagInput = document.getElementById('tagInput');
            addTag(tagInput.value);
            tagInput.value = '';
        } else if (event.type === 'click') {
            addTag(event.target.innerText);
        }
    }

    function addTag(tag) {
        if (!selectedTags.includes(tag)) {
            selectedTags.push(tag);
            updateDisplay();
        }
    }

    function removeTag(tag) {
        var index = selectedTags.indexOf(tag);
        if (index > -1) {
            selectedTags.splice(index, 1);
            updateDisplay();
        }
    }

    function updateDisplay() {
        var displayDiv = document.getElementById('tagsDisplay');
        displayDiv.innerHTML = '';
        for (var i = 0; i < selectedTags.length; i++) {
            var tag = selectedTags[i];
            displayDiv.innerHTML += `
            <span class="btn btn-primary btn-sm" style="margin-right: 5px; margin-bottom: 5px;">
                ${tag}
                <span class="close" style="margin-left: 5px;" onclick="event.stopPropagation(); removeTag('${tag}')">&times;</span>
            </span>`;
        }
        document.getElementById('tagsField').value = selectedTags.join(' ');
    }

    // 初始化已经选择的标签
    var initialTags = document.getElementById('tagsField').value;
    if (initialTags) {
        selectedTags = initialTags.split(' ');
        updateDisplay();
    }
</script>

{% endblock %}